### ISSUE TITLE
update InvalidContentType error message to include newly-acceptable types

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/husky#117]
**Versions**

0.15.0

**Additional context**

0.15.0 ships with [an expanded list of allowable content types](https://github.com/honeycombio/husky/pull/112/files#diff-ba431ec94871df83d34cc8907a9583556d974a802e83b0863c13d5e90037cc4aR87), but the error returned for still-invalid types reports that "only 'application/protobuf' is supported".

**Comment by JamieDanielson** [comment]
This was resolved in #121 

previously the error was hardcoded `"invalid content-type - only 'application/protobuf' is supported"`
now the error uses a list of supported content types `"unsupported content-type, valid types are: " + strings.Join(GetSupportedContentTypes()"`
