### ISSUE TITLE
Fallback to dataset setting for logs

### ISSUE THREAD

**Issue by cartermp** [honeycombio/husky#118]
There is a use case for logs that doesn't necessarily involve a service. Logs can come from somewhere else, then be forwarded via a collector and turned into OTLP logs.

If you're using Classic Honeycomb today, this use case is actually handled well, because the dataset is required. But if you use Environments, the dataset where the logs are sent to is called `unknown_service` even if you have the dataset specified.

There's a broader question of if we should respect dataset in the event of a a non-unknown `service.name` for all signals. But at least for Logs, there's a clear use case IMO.

**Comment by robbkidd** [comment]
Idea for routing logs:
* if service.name set in a log entry, that’s the destination dataset
* no service.name attribute? use the x-honeycomb-dataset header value
* no x-honeycomb-dataset? use “unknown_log_source”?
  * let’s look at [the log spec](https://opentelemetry.io/docs/reference/specification/logs/data-model/)!
