### ISSUE TITLE
Should we use jsoniter instead of encoding/json?

### ISSUE THREAD

**Issue by cartermp** [honeycombio/husky#147]
From @ianwilkes in a recent chat:

> but also we should use `jsoniter`, not `json`

Orthogonally to #145 and #146 we may want to look into using https://github.com/json-iterator/go. It looks like it can be a very simple drop-in replacement.

`jsoniter` purports to be over 150% faster at encoding in their benchmark, and json encoding is on our hot path for ingest. Does that track, or is it just some number on a table?

We could also use shepherd profiles in pyroscope to get a better sense of the data.

**Comment by ianwilkes** [comment]
We already use jsoniter in many places in hound for efficiency reasons - for example, for encoding query results in retriever client. The time and memory savings are real.

**Comment by pkanal** [comment]
Closed by #145 & #146 being merged
