### ISSUE TITLE
E&S: set default unknown_service if service.name is empty or missing

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/husky#41]
In the E&S world currently, husky will only throw a "missing service.name" error if a particular resource span is missing a resource entirely or if the resource does not have a service.name attribute. We should return the same error when resource and attribute exist, but the attribute value is an empty string.

**Update**: In both scenarios of missing service name attribute and empty service name attribute, set the service name to `unknown_service` instead of erroring and dropping the data.

**Comment by JamieDanielson** [comment]
After further internal discussion, it was decided that it may be better to set `unknown_service` than to error on a missing service name and drop the events. Therefore, husky will be updated to reflect the new decision and fall back to default `unknown_service` in the case of a missing or empty service name attribute.
