### ISSUE TITLE
truncate unknown_service* dataset for E&S

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/husky#45]
If a trace comes in that starts with `unknown_service`, e.g. `unknown_service:java`, keep the service name as-is but truncate the dataset to simply `unknown_service` (use `defaultServiceName`).

- [x] update husky
- [x] bump husky in shepherd
- [x] what happens if we send `foounknown_service:blah/blah&bar` as `resource.service-name`

**Comment by vreynolds** [comment]
> what happens if we send `foounknown_service:blah/blah&bar` as `resource.service-name`

dataset created as `foounknown_service-blah-blah-bar`
event `service.name` still `foounknown_service:blah/blah&bar`

seems ok if the service name is that wonky
