### ISSUE TITLE
Which level of attributes should win when merging: Resource or Span?

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/husky#73]
On the occasion that a Span has an attribute name that matches a Resource attribute, [the current implementation has the Resource attribute's value winning](https://github.com/honeycombio/husky/blob/v0.10.4/otlp/trace.go#L129-L136) when attributes are gathered onto an event. Should that behavior remain? Or should we update the transform to assign Span attributes after Resource attributes so that the more specific value set is the one that wins? Raising the question because this precedence order will grow in layers if OTEP 201 is accepted and the Scope (neé InstrumentationLibrary) interstitial layer gets attributes, too.

**Comment by MikeGoldsmith** [comment]
I think span should win - specific > broad. You may want to override an attribute on a given span.

**Comment by robbkidd** [comment]
> specific > broad

![I agree.](https://user-images.githubusercontent.com/517302/166710955-20de1092-0e0c-4d34-adf3-61c93894508f.gif)
